type: python
runtime: ghcr.io/nextmv-io/runtime/gamspy:latest
files:
  - main.py
  - model.py
  - visualizations.py
python:
  pip-requirements: requirements.txt
execution:
  entrypoint: main.py
configuration:
  content:
    format: multi-file
    multi-file:
      input:
        path: inputs
      output:
        solutions: outputs/solutions
        statistics: outputs/statistics/statistics.json
        assets: outputs/assets/assets.json
  options:
    items:
      - name: risk_weight_limit
        description: Maximum allowable average risk weight for the portfolio
        required: false
        option_type: float
        default: 0.5
        additional_attributes:
          min: 0
          max: 1
          step: 0.01
        ui:
          control_type: slider
          display_name: Risk Weight Limit
      - name: verbose
        description: Whether to print detailed segment and asset-level results
        required: false
        option_type: bool
        default: false
        ui:
          display_name: Verbose Output
      - name: target
        description: Profit target (minimum profit as fraction of maximum) for CVaR minimization in objective_1
        required: false
        option_type: float
        default: 0.9
        additional_attributes:
          min: 0.05
          max: 1.00
          step: 0.05
        ui:
          control_type: slider
          display_name: Profit Target
      - name: confidence_level
        description: Confidence level for CVaR calculation
        required: false
        option_type: float
        default: 0.95
        additional_attributes:
          min: 0.5
          max: 0.99
          step: 0.01
        ui:
          control_type: slider
          display_name: CVaR Confidence Level
      - name: total_num_decrease
        description: Maximum fraction of segments that can decrease exposure
        required: false
        option_type: float
        default: 0.3
        additional_attributes:
          min: 0
          max: 1
          step: 0.05
        ui:
          control_type: slider
          display_name: Max Decrease Fraction
      - name: total_num_increase
        description: Maximum fraction of segments that can increase exposure
        required: false
        option_type: float
        default: 0.4
        additional_attributes:
          min: 0
          max: 1
          step: 0.05
        ui:
          control_type: slider
          display_name: Max Increase Fraction
      - name: total_num_change
        description: Maximum fraction of segments that can change (increase or decrease)
        required: false
        option_type: float
        default: 0.5
        additional_attributes:
          min: 0
          max: 1
          step: 0.05
        ui:
          control_type: slider
          display_name: Max Change Fraction
      - name: export_latex
        description: Export model formulation to LaTeX
        required: false
        option_type: bool
        default: false
        ui:
          display_name: Export LaTeX
